name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stats.svg
          base: header, activity, community, repositories
          plugin_lines: no
          config_display: large

      - name: Most Used Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: top-langs.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_repos_limit: 0
          plugin_languages_details: percentage
          config_display: large

      - name: Generate 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Move 3D profile
        run: |
          mv ./profile-3d-contrib/profile-night-rainbow.svg ./profile-3d.svg
          rm -rf ./profile-3d-contrib

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A .
          git diff --staged --quiet || (git commit -m "Update metrics" && git push)
